name: Publish releases
on:
  release:
    types: [published]
jobs:
  cratesio:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: cargo publish
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
